name: App With Github Actions with Docker CI/CD

on:
  # workflow_dispatch
  push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: lecturer-yonggishin/app-with-argocd
        ref: main
        token: ${{ secrets.TOKEN }}
        
    - name: Set up Image
      run: |
        sed -i "s%image: nginx:1.25%image: nginx:latest%" ./argocd-deployment.yaml
